export enum ROLES {
  BASIC = 'BASIC',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  EDITOR = 'EDITOR',
  MODERATOR = 'MODERATOR',
  GUEST = 'GUEST',
  SUPERVISOR = 'SUPERVISOR',
  CONTRIBUTOR = 'CONTRIBUTOR',
  MANAGER = 'MANAGER',
  DEVELOPER = 'DEVELOPER',
  OWNER = 'OWNER',
}

export enum ACCESS_LEVEL {
  MANTEINER = 40,
  OWNDER = 50,
}
